site_name: Hytale Formats Wiki
site_url: https://bjtmastermind.github.io/hytale-formats-wiki/
theme:
    name: material
    features:
        - navigation.sections
        - navigation.indexes
extra_css:
    - css/treeview.css
    - css/table.css
extra_javascript:
    - js/add_icons.js
nav:
    - Home: index.md
    - Pages:
        - World formats:
            - Chunk format:
                - wiki/Chunk_format/index.md
                - Block format:
                    - wiki/Chunk_format/Block_format/index.md
                    - Octree structure: wiki/Chunk_format/Block_format/Octree_structure.md
                - BlockChunk format: wiki/Chunk_format/BlockChunk_format.md
                - BlockHealthChunk format: wiki/Chunk_format/BlockHealthChunk_format.md
                - BlockPhysics format: wiki/Chunk_format/BlockPhysics_format.md
                - EnvironmentChunk format: wiki/Chunk_format/EnvironmentChunk_format.md
                - Fluid format: wiki/Chunk_format/Fluid_format.md
            - Player format: wiki/Player_format.md
            - Region file format: wiki/Region_file_format.md
            - World Config format: wiki/World_Config_format.md
        - Multiplayer formats:
            - Bans format: wiki/Bans_format.md
            - Permissions format: wiki/Permissions_format.md
            - Whitelist format: wiki/Whitelist_format.md
        - Other formats:
            - Barter Shop State format: wiki/Barter_Shop_State_format.md
            - Block Counter format: wiki/Block_Counter_format.md
            - Block Map Markers format: wiki/Block_Map_Markers_format.md
            - Client Metadata format: wiki/Client_Metadata_format.md
            - Instance Data format: wiki/Instance_Data_format.md
            - Memories format: wiki/Memories_format.md
            - Mods Config format: wiki/Mods_Config_format.md
            - Prefab Edit Session format: wiki/Prefab_Edit_Session_format.md
            - Prefab format: wiki/Prefab_format.md
            - Reputation Data format: wiki/Reputation_Data_format.md
            - Spawn Suppression Controller format: wiki/Spawn_Suppression_Controller_format.md
            - Time format: wiki/Time_format.md
            - Warps format: wiki/Warps_format.md
            - World structure: wiki/World_structure.md
        - Changelogs:
            - 2026.01.13-50e69c385: wiki/changelogs/2026.01.13-50e69c385.md
            - 2026.01.15-c04fdfe10: wiki/changelogs/2026.01.15-c04fdfe10.md
            - 2026.01.17-4b0f30090: wiki/changelogs/2026.01.17-4b0f30090.md
            - 2026.01.24-6e2d4fc36: wiki/changelogs/2026.01.24-6e2d4fc36.md
            - 2026.01.27-734d39026: wiki/changelogs/2026.01.27-734d39026.md
        - Version history: wiki/Version_history.md
        - Development version history: wiki/Development_version_history.md
    - View on GitHub: https://github.com/bjtmastermind/hytale-formats-wiki
plugins:
    - search
    - exclude:
        glob:
            - images/**/*.md
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.superfences
